server:
  port: 8081
spring:
  rabbitmq:
    username: user
    password: password
    virtual-host: /
    host: 139.196.112.185
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true
  cloud:
    consul:
      host: 139.196.112.185
      port: 8500
#      discovery:
#        healthCheckPath: /actuator/health
#        healthCheckInterval: 15s
